FEAT : PostgreSql PreparedStatement 내 EnumType 쿼리 매핑 구현체 추가
- 해결한 원인 에러 :
  ```
  org.postgresql.util.PSQLException: ERROR: operator does not exist: app_dev.message_type = bytea
    Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  ```